'use strict';
const $=id=>document.getElementById(id), reports={}, labels={ok:'확인',warning:'주의',error:'오류',unknown:'미확인',excluded:'대상 외',offline:'최근 관측 없음'};
const groups=[['input','01','기록·기준'],['collect','02','수집·전달'],['refine','03','정제'],['memory','04','기억'],['use','05','검사·재사용']];
let device='work', selected='center', current=null, loading=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const age=r=>r&&Number.isFinite(Date.parse(r.checked_at))?(Date.now()-Date.parse(r.checked_at))/1000:Infinity;
const fresh=r=>age(r)>=-300&&age(r)<=2700;
const num=n=>Number.isFinite(n)?n.toLocaleString('ko-KR'):'—';
const date=s=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'관측 없음';
const ageText=r=>!r?'관측 없음':age(r)<-300?'기기 시각 확인':fresh(r)?`${Math.max(0,Math.floor(age(r)/60))}분 전 관측`:`${date(r.checked_at)} 이후 미확인`;
function inspect(id){selected=id;const n=current?.nodes.find(n=>n.id===id);if(!n)return;document.querySelectorAll('.node').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));const box=$('inspector');box.replaceChildren(el('p','CONNECTION DETAIL','eyebrow'),el('span',labels[n.state]||'미확인','state'),el('h3',n.title),el('p',n.detail));if(n.count!==null)box.append(el('p',`${num(n.count)} ${n.unit||'개'} · ${date(n.latest)}`));else if(n.latest)box.append(el('p',date(n.latest)));if(n.action){box.append(el('h4','다음 확인'),el('p',n.action));}const links=current.edges.filter(e=>e.source===id||e.target===id);if(links.length){box.append(el('h4','연결 근거'));const list=el('ul');for(const e of links){const target=current.nodes.find(n=>n.id===(e.source===id?e.target:e.source));list.append(el('li',`${target?.title||'항목'} · ${e.label} (${e.evidence==='observed'?'자료·실행 확인':e.evidence==='excluded'?'연결 없음':'설정 확인'})`));}box.append(list);}draw();}
function draw(){const svg=$('wires'),graph=$('graph');svg.replaceChildren();svg.setAttribute('width',String($('columns').offsetWidth+32));svg.setAttribute('height',String($('columns').offsetHeight+54));if(!current||innerWidth<=650)return;const bounds=graph.getBoundingClientRect();for(const edge of current.edges){const a=document.querySelector(`[data-id="${edge.source}"]`),b=document.querySelector(`[data-id="${edge.target}"]`);if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();const forward=br.left>=ar.left;const x1=(forward?ar.right:ar.left)-bounds.left+graph.scrollLeft,y1=ar.top+ar.height/2-bounds.top+graph.scrollTop,x2=(forward?br.left:br.right)-bounds.left+graph.scrollLeft,y2=br.top+br.height/2-bounds.top+graph.scrollTop;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} C ${x1+(forward?25:-25)} ${y1}, ${x2+(forward?-25:25)} ${y2}, ${x2} ${y2}`);if(edge.evidence!=='observed')path.setAttribute('stroke-dasharray','3 4');path.setAttribute('class',`${edge.state==='warning'||edge.state==='error'?'warning ':''}${edge.source===selected||edge.target===selected?'active':''}`);svg.append(path);}}
function render(){for(const role of ['home','work']){$(`${role}-age`).textContent=ageText(reports[role]);document.querySelector(`[data-device="${role}"]`).setAttribute('aria-pressed',String(role===device));}const r=reports[device];$('updated').textContent=`${device==='home'?'집':'회사'} · ${ageText(r)}`;const valid=fresh(r);$('notice').classList.toggle('warn',!valid||!!r?.issues.length);$('notice').textContent=!r?'이 기기의 관측 기록을 아직 받지 못했습니다. 기록이 도착하면 지도가 표시됩니다.':!valid?'관측 갱신이 멈춰 현재 상태는 미확인입니다. 아래 개수는 마지막 기록이며, 절전과 장애를 구분할 수 없습니다.':r.issues.length?`${r.issues.length}곳의 확인이 필요합니다. 같은 문제가 두 번 이어질 때 먼지가 알립니다.`:'관측 범위에서 감지된 문제는 없습니다. 미확인·대상 외 연결은 따로 확인하세요.';
if(!r){current=null;$('columns').replaceChildren();$('wires').replaceChildren();for(const k of ['messages','memory','issues','delta'])$(k).textContent='—';$('attention').replaceChildren(el('p','관측 기록이 없어 정상 여부를 판단할 수 없습니다.','empty'));$('bars').replaceChildren();$('inspector').replaceChildren(el('h3','관측 대기 중'));return;}
current={...r,nodes:r.nodes.map(n=>({...n,state:!valid&&n.state!=='excluded'?'unknown':n.state}))};$('messages').textContent=num(r.index.messages);const memory=r.nodes.filter(n=>n.group==='memory');$('memory').textContent=num(memory.reduce((s,n)=>s+(n.count||0),0));$('issues').textContent=valid?num(r.issues.length):'미확인';const history=(r.history||[]).filter(h=>Number.isFinite(h.messages));const delta=history.length>1?history.at(-1).messages-history[0].messages:null;$('delta').textContent=delta===null?'—':`${delta>0?'+':''}${num(delta)}`;$('period').textContent=history.length>1?`${date(history[0].at)}부터 · 메시지 순변화`:'두 번 이상 관측하면 비교합니다';
$('columns').replaceChildren();for(const [group,step,title] of groups){const col=el('div',undefined,'column');const h=el('h3',step);h.append(el('b',title));col.append(h);for(const n of current.nodes.filter(n=>n.group===group)){const b=el('button',undefined,'node');b.dataset.id=n.id;b.dataset.state=n.state;b.setAttribute('aria-pressed',String(n.id===selected));b.setAttribute('aria-label',`${n.title}, ${labels[n.state]}`);const name=el('span',undefined,'name');name.append(el('span',n.state==='ok'?'●':n.state==='warning'||n.state==='error'?'◐':n.state==='excluded'?'—':'○','dot'),document.createTextNode(n.title));b.append(name,el('span',n.count===null?labels[n.state]:`${num(n.count)} ${n.unit||'개'}`,'count'));b.onclick=()=>inspect(n.id);col.append(b);}$('columns').append(col);}
$('attention').replaceChildren();if(!valid)$('attention').append(el('p','현재 상태를 판단하려면 새 관측이 필요합니다.','empty'));else if(!r.issues.length)$('attention').append(el('p','감지된 문제 없음. 미확인 항목은 지도에서 근거를 확인하세요.','empty'));else for(const issue of r.issues){const b=el('button',undefined,'issue');b.append(el('strong',`${labels[issue.state]} · ${issue.title} ↗`),el('span',issue.action));b.onclick=()=>{inspect(issue.id);$('inspector').scrollIntoView({block:'nearest'});};$('attention').append(b);}
$('bars').replaceChildren();const max=Math.max(1,...memory.map(n=>n.count||0));for(const n of memory){const row=el('div',undefined,'bar-row'),bar=el('i'),fill=el('span');fill.style.width=`${100*(n.count||0)/max}%`;bar.append(fill);row.append(el('span',n.title),bar,el('b',num(n.count)));$('bars').append(row);}inspect(current.nodes.some(n=>n.id===selected)?selected:current.nodes[0]?.id);requestAnimationFrame(draw);}
async function refresh(){if(loading)return;loading=true;$('refresh').disabled=true;await Promise.all(['home','work'].map(async role=>{try{const response=await fetch(`data/${role}.json?t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('unavailable');const r=await response.json();if(r.schema!==1||r.device!==role||!Array.isArray(r.nodes)||!r.nodes.length||!Array.isArray(r.edges)||!Array.isArray(r.issues)||!r.index)throw Error('invalid report');reports[role]=r;}catch{ /* Existing evidence keeps its original timestamp. */ }}));loading=false;$('refresh').disabled=false;render();}
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;render();});$('refresh').onclick=refresh;window.addEventListener('resize',draw);setInterval(refresh,60000);setInterval(render,30000);refresh();
