import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {makeWorld,obstacles,box} from './geometry.js';
import {roomRendering} from './rendering.js';
import {prepareMaterials} from './materials.js';
import {updateWorld} from './furnishings.js';
import {preload,actor} from './actors.js';
import {route,angleDelta,blocked} from './navigation.js';
const $=id=>document.getElementById(id),host=$('sim-canvas'),status=$('sim-status'),shell=$('simulation'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let graphicsLost=false;let paused=reduced.matches,visible=true,shown=true,ready=false,phase=0,externalWait=false,auto=false,phaseAge=0,time=0,last=0,raf=0,selected=0,following=false;
let drawing,renderer,controls,camera,scene,transferMesh,transferProgress=0,transferDwell=0;const people=[];
const roleNames={read:'근거 읽기',write:'수정·기록',verify:'조건 대조',present:'방향·근거 제시',carry:'자료 전달',file:'서가에 정리',observe:'흐름 관찰',agree:'확인·끄덕임',wait:'이 갈래만 응답 대기',survey:'전체 흐름 살피기',challenge:'반례·다른 조건 제시',pickup:'떨어진 서류 줍기'};
const feelingNames={focused:'집중',curious:'궁금함',calm:'차분함',pleased:'기쁨·안도',disappointed:'난점에 잠깐 실망',brooding:'깊이 생각',surprised:'새로운 발견',relieved:'실마리를 찾은 안도'};
const roster=[['howl','하울',1.7,-4.4,-.45],['dust','연구 먼지',.9,-2.4,.6],['dust','사서 먼지',.9,-3.1,-1.8],['dust','실행 먼지',.9,-2.4,3.2],['kitty','키티 · 개선',1.3,3.6,-.45],['kitty','키티 · 분신',1.3,-3.3,1.6],['kuromi','쿠로미 · 검증',1.35,4.05,1.6],['kuromi','쿠로미 · 분신',1.35,4.7,.6],['chococat','초코캣',1.25,.85,3.6]];
// Every task is a place, a facing target, and an action. Representatives alone join the table.
const job=(x,z,lookX,lookZ,action,feeling='focused')=>({x,z,lookX,lookZ,action,feeling});
function jobs(id){const base=[
 [job(-4.6,.3,-3.7,.4,'read'),job(-4.25,-1.6,0,-.5,'survey','curious'),job(-4.25,-1.6,0,-.5,'present','calm')],
 [job(-2.6,.5,-3.7,.45,'read'),job(-1.9,1.4,0,-.5,'carry','curious')],
 [job(-3.2,-2.2,-3.2,-2.9,'file'),job(-1.4,-2.7,-.55,-2.95,'read')],
 [job(-2.5,3.3,-3.25,2.5,'pickup','curious'),job(1.9,2.3,3.6,.5,'carry')],
 [job(3.6,-.45,3.6,.5,'write'),job(2.5,.45,3.6,.5,'read','curious')],
 [job(-3.3,1.6,-3.25,2.5,'write'),job(-4.35,2.35,-3.25,2.5,'read')],
 [job(4.05,1.6,4.05,2.45,'verify'),job(2.65,2.45,4.05,2.45,'agree','pleased')],
 [job(4.7,.5,3.6,.5,'verify'),job(4.2,-.3,3.6,.5,'read')],
 [job(.85,3.6,3.3,1,'observe','curious'),job(-1.8,2.2,-3.7,.45,'write'),job(1.9,1.7,4.05,2.45,'observe','curious')]
 ];
 if(externalWait&&id===1)return [job(-2.6,.5,-3.7,.45,'wait','calm')];
 if(phase===0&&id===4)return [job(3.6,-.45,3.6,.5,'read','curious'),job(2.5,.5,3.6,.5,'present','curious')];
 if(phase===2){if(id===4)return [job(-1.6,-.45,0,-.5,'present','curious')];if(id===1)return [job(-.2,1.12,0,-.5,'read'),job(-.2,1.12,0,-.5,'present')];if(id===6)return [job(1.63,-.45,0,-.5,'verify'),job(1.63,-.45,-1.6,-.45,'challenge','curious'),job(1.63,-.45,-1.6,-.45,'agree','pleased')];}
 if(phase===3){if(id===4)return [job(2.6,1.5,3.35,2.1,'carry'),job(2.6,1.5,3.35,2.1,'present','pleased')];if(id===6)return [job(3.35,1.85,2.6,1.5,'verify'),job(3.35,1.85,2.6,1.5,'agree','pleased')];}
 if(phase===4&&id===2)return [job(-1.4,-2.65,-.55,-2.95,'carry'),job(-3.2,-2.2,-3.2,-2.9,'file','pleased')];
 return base[id];
}
function assign(p){const list=jobs(p.id);p.task=p.manual?.task||list[p.round%list.length];p.path=route(p.root.position.x,p.root.position.z,p.task.x,p.task.z);p.age=0;p.hold=p.manual?14.4:15.5+(p.id*1.37)%4;p.stage=p.path.length?'turn':'work';p.delay=.22+(p.id%3)*.09;}
function schedule(p){
 const pose=p.getPerformance?.();
 if(!paused&&(p.recovery||pose?.cross>.02||pose?.crouch>.02)){
  if(!p.recovery)p.recovery={name:pose.name,age:Math.max(pose.age,pose.name==='crossleg'?9.5:3.4),end:pose.name==='crossleg'?13.2:6.1,task:p.task};
  p.path=[];p.speed=0;return;
 }
 p.recovery=null;assign(p);
}
const sceneNames={disappointed:'이마를 짚고 다시 집중',brooding:'턱을 괴고 깊이 생각',pickup:'몸을 낮춰 서류 줍기',crossleg:'잠깐 바닥에 앉기',idea:'실마리를 찾고 제안',read:'읽고 확인하기'};
function performanceFor(p){
 if(p.task.action==='wait')return '';
 if(p.task.action==='pickup')return 'pickup';
 if(p.key==='howl')return p.task.action==='read'?(p.round%2?'brooding':'disappointed'):p.task.action==='present'?'idea':'read';
 if(p.key==='dust')return p.id===2&&p.round%2?'crossleg':p.task.action==='file'?'idea':p.id===1&&p.round%2?'brooding':'read';
 if(p.key==='kitty')return p.id===4?'idea':'brooding';
 if(p.key==='kuromi')return p.task.action==='agree'?'idea':'brooding';
 return p.task.action==='observe'?'brooding':'read';
}
function playScene(name){
 if(!ready)return;
 const id={disappointed:0,brooding:6,pickup:3,crossleg:2,idea:4,read:1}[name];
 if(id===undefined)return;
 const p=people[id],needsFloor=['pickup','crossleg'].includes(name),pos=p.root.position;
 const candidates=needsFloor?[[.2,2.65],[-1.6,2.05],[1.65,2.6],[-2.2,3.1]]:[[pos.x,pos.z],[-.4,2.4]];
 const free=candidates.filter(([x,z])=>!blocked(x,z)&&people.every(q=>q===p||Math.hypot(q.root.position.x-x,q.root.position.z-z)>.85));
 if(!free.length){status.hidden=false;status.textContent='장면을 펼칠 자리를 기다리고 있습니다. 잠시 후 다시 눌러 주세요.';return;}
 const [x,z]=free.sort((a,b)=>Math.hypot(a[0]-pos.x,a[1]-pos.z)-Math.hypot(b[0]-pos.x,b[1]-pos.z))[0];
 p.manual={name,task:job(x,z,x,z+1,name==='pickup'?'pickup':name==='crossleg'?'observe':'read','calm')};
 schedule(p);focusPerson(id);following=true;
 if(paused){
  p.root.position.set(x,.03,z);p.root.rotation.y=0;p.path=[];p.speed=0;p.stage='work';p.age=name==='pickup'?2.25:4;
  p.update(time+p.id*1.713,0,p.task.action,'calm',p.gait||0,Infinity,{yaw:0,pitch:0,age:p.age,performance:name});p.currentPerformance=name;p.feeling=p.getPerformance?.()?.face||'calm';
  focusPerson(id);following=true;
 }
 document.querySelectorAll('[data-performance]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.performance===name)));updateLabel();
}
function updatePeople(dt){for(const p of people){
 if(p.recovery){
  const r=p.recovery;r.age+=dt;p.age=r.age;p.stage='work';p.action=r.task.action;
  p.update(time+p.id*1.713,0,r.task.action,r.task.feeling,p.gait||0,dt,{yaw:0,pitch:0,age:r.age,performance:r.name,recovering:true});
  p.currentPerformance=r.name;p.feeling=p.getPerformance().face;
  if(r.age>=r.end){p.recovery=null;assign(p);}continue;
 }
 p.age+=dt;let action=p.task.action,feeling=p.task.feeling;const pos=p.root.position;if(p.path.length){const target=p.path[0],dx=target[0]-pos.x,dz=target[1]-pos.z,dist=Math.hypot(dx,dz);if(dist<.09){p.path.shift();continue;}const yaw=Math.atan2(dx,dz),turn=angleDelta(p.root.rotation.y,yaw);p.root.rotation.y+=T.MathUtils.clamp(turn,-dt*3,dt*3);const remaining=dist+p.path.length*.28,desired=p.age<p.delay||Math.abs(turn)>.7?0:Math.min(.7,remaining*1.3),near=people.some(q=>q!==p&&(q.speed<.05||q.id<p.id)&&Math.hypot(q.root.position.x-pos.x-dx/dist*.18,q.root.position.z-pos.z-dz/dist*.18)<.56);p.blockedAge=near?(p.blockedAge||0)+dt:0;if(p.blockedAge>.8){const avoid=people.filter(q=>q!==p&&(q.speed<.05||q.id<p.id)).map(q=>({x:q.root.position.x,z:q.root.position.z,r:.80}));const alternative=route(pos.x,pos.z,p.task.x,p.task.z,avoid);if(alternative.length)p.path=alternative;p.blockedAge=0;}p.speed=T.MathUtils.damp(p.speed,near?0:desired,4,dt);const d=Math.min(dist,p.speed*dt);const nx=pos.x+dx/dist*d,nz=pos.z+dz/dist*d;const touching=people.some(q=>q!==p&&Math.hypot(q.root.position.x-nx,q.root.position.z-nz)<.47);if(!touching){pos.x=nx;pos.z=nz;}else p.speed=0;p.stage=p.speed>.03?'walk':'turn';action=p.task.action==='wait'||p.task.action==='pickup'||p.manual?.name==='crossleg'?'observe':'carry';if(!p.path.length)p.age=0;}else{p.speed=T.MathUtils.damp(p.speed,0,7,dt);const yaw=Math.atan2(p.task.lookX-pos.x,p.task.lookZ-pos.z);p.root.rotation.y+=T.MathUtils.clamp(angleDelta(p.root.rotation.y,yaw),-dt*2,dt*2);if(p.stage!=='work'){p.stage='work';p.age=0;}if(p.age>p.hold){if(p.manual)document.querySelector(`[data-performance="${p.manual.name}"]`)?.setAttribute('aria-pressed','false');p.manual=null;p.round++;assign(p);}}
 p.action=action;p.feeling=feeling;let look={x:p.task.lookX,z:p.task.lookZ,y:p.h*.60};if((p.key==='chococat'&&action==='observe')||(p.key==='howl'&&action==='survey')){p.watchAge=(p.watchAge||0)+dt;if(p.watchId===undefined||p.watchAge>3.2){const choices=people.filter(q=>q!==p),moving=choices.filter(q=>q.speed>.08);p.watchId=(moving.length?moving:choices).sort((a,b)=>a.root.position.distanceToSquared(pos)-b.root.position.distanceToSquared(pos))[0]?.id;p.watchAge=0;}const target=people[p.watchId];if(target)look={x:target.root.position.x,z:target.root.position.z,y:target.h*.7};}const attention={yaw:T.MathUtils.clamp(angleDelta(p.root.rotation.y,Math.atan2(look.x-pos.x,look.z-pos.z)),-.65,.65),pitch:Math.atan2(look.y-p.h*.7,Math.max(.5,Math.hypot(look.x-pos.x,look.z-pos.z)))};p.gait=(p.gait||0)+p.speed*dt*(p.key==='howl'?11:p.key==='dust'?15:18);attention.age=p.age;attention.performance=p.stage==='work'?(p.manual?.name||performanceFor(p)):'';p.update(time+p.id*1.713,p.speed,action,feeling,p.gait,dt,attention);p.currentPerformance=attention.performance;p.feeling=p.getPerformance?.()?.name?p.getPerformance().face:feeling;}}
function updateTransfer(dt){if(!transferMesh||!ready)return;transferMesh.visible=false;if(phase!==3)return;const from=people[4],to=people[6];if(!from.prop||!to.prop)return;if(from.stage==='work'&&to.stage==='work'&&from.root.position.distanceTo(to.root.position)<1.6){transferDwell+=dt;if(transferDwell>.8)transferProgress=Math.min(1,transferProgress+dt/1.1);}if(transferProgress>0&&transferProgress<1){from.prop.visible=false;to.prop.visible=false;transferMesh.visible=true;const a=from.prop.getWorldPosition(new T.Vector3()),b=to.prop.getWorldPosition(new T.Vector3()),t=transferProgress*transferProgress*(3-2*transferProgress);transferMesh.position.lerpVectors(a,b,t);transferMesh.position.y+=Math.sin(t*Math.PI)*.10;transferMesh.quaternion.slerpQuaternions(from.root.quaternion,to.root.quaternion,t);}else if(transferProgress>=1){from.prop.visible=false;to.prop.visible=true;}}
function setPhase(value,wait=externalWait){document.querySelectorAll('[data-performance]').forEach(b=>b.setAttribute('aria-pressed','false'));phase=value;externalWait=wait;phaseAge=0;transferProgress=paused&&phase===3?1:0;transferDwell=0;for(const p of people){p.manual=null;p.round=0;schedule(p);if(paused){const last=p.path.at(-1);if(last)p.root.position.set(last[0],.03,last[1]);p.path=[];p.speed=0;p.stage='work';p.root.rotation.y=Math.atan2(p.task.lookX-p.root.position.x,p.task.lookZ-p.root.position.z);p.action=p.task.action;p.feeling=p.task.feeling;p.update(time+p.id*1.713,0,p.task.action,p.task.feeling,p.gait||0,Infinity,{yaw:0,pitch:0,age:3,performance:performanceFor(p)});p.currentPerformance=performanceFor(p);p.feeling=p.getPerformance?.()?.face||p.task.feeling;}}updateTransfer(0);updateLabel();}
function updateLabel(){const p=people[selected];if(!p)return;$('sim-agent-name').textContent=p.name;$('sim-agent-action').textContent=(p.stage==='walk'?'자료를 들고 이동 → ':p.stage==='turn'?'시선을 돌리고 출발 준비 → ':'')+(roleNames[p.action||p.task.action])+' · '+feelingNames[p.feeling||p.task.feeling]+(p.currentPerformance?' · '+sceneNames[p.currentPerformance]:'');$('sim-stage').textContent=`${phase+1}/5 · ${['다음 일 발견','분신 협업','쟁점 조율','검증·인계','기억·다음 일'][phase]}`;}
function setPause(value){if(graphicsLost&&!value)return;paused=value;if(!paused&&ready)status.hidden=true;$('sim-pause').textContent=paused?'움직임 재생':'움직임 정지';$('sim-pause').setAttribute('aria-pressed',String(paused));}
function orbit(az=0,polar=0,zoom=1){following=false;const offset=camera.position.clone().sub(controls.target),s=new T.Spherical().setFromVector3(offset);s.theta+=az;s.phi=T.MathUtils.clamp(s.phi+polar,controls.minPolarAngle,controls.maxPolarAngle);s.radius=T.MathUtils.clamp(s.radius*zoom,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();}
const viewTargets={whole:[0,.7,0,16.8],meeting:[0,.7,-.5,7],knowledge:[-3.1,1,-1.5,7.5],parallel:[3.5,.65,1.3,8],howl:[-3.7,.9,0,7],studio:[3.5,.65,1.3,8],observer:[0,.5,2.7,8]};
function focusView(key='whole'){following=false;const [x,y,z,baseRadius]=viewTargets[key]||viewTargets.whole;controls.target.set(x,y,z);const radius=key==='whole'?Math.max(baseRadius,7.5/(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect)):baseRadius;const s=new T.Spherical(Math.min(28,radius),Math.PI/4,.28);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();}
function focusPerson(id){selected=id;const p=people[id];if(!p)return;following=false;controls.target.copy(p.root.position).add(new T.Vector3(0,p.h*.52,0));scene.updateMatrixWorld(true);const ray=new T.Raycaster(),others=people.filter(q=>q!==p).map(q=>q.root);for(const root of others)root.traverse(o=>{if(o.isSkinnedMesh)o.computeBoundingSphere();});const faceHeight={howl:.92,kitty:.587,kuromi:.516,chococat:.64,dust:.66}[p.key];const facePoints=[-.12,0,.12].map(x=>p.root.localToWorld(new T.Vector3(x*p.h,faceHeight*p.h,(p.key==='howl'?.06:.24)*p.h)));let best=null,bestHits=Infinity;for(const angle of [.45,-.65,1.1,-1.1,1.65,-1.65]){const origin=controls.target.clone().add(new T.Vector3().setFromSpherical(new T.Spherical(Math.max(2.1,p.h*2.2),Math.PI/3,p.root.rotation.y+angle)));let count=0;for(const point of facePoints){ray.set(origin,point.clone().sub(origin).normalize());ray.far=origin.distanceTo(point)-.1;count+=ray.intersectObjects(others,true).length;}if(count<bestHits){best=origin;bestHits=count;}if(!count)break;}camera.position.copy(best);controls.update();document.querySelectorAll('[data-person]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.person)===id)));updateLabel();}
function resize(){if(!renderer)return;const r=host.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);drawing?.resize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=camera.aspect<1.2?45:36;camera.updateProjectionMatrix();if(!ready)focusView();}
function tick(now){raf=requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(document.hidden||!visible||!shown||graphicsLost)return;drawing?.observeFrame?.(dt);if(ready&&!paused){time+=dt;phaseAge+=dt;updateWorld(time);updatePeople(dt);updateTransfer(dt);if(auto&&phaseAge>24){window.dispatchEvent(new CustomEvent('simulation-next'));}if(Math.floor(time*3)!==Math.floor((time-dt)*3))updateLabel();}if(following&&people[selected]){const desired=people[selected].root.position.clone().add(new T.Vector3(0,people[selected].h*.52,0)),delta=desired.sub(controls.target).multiplyScalar(.10);controls.target.add(delta);camera.position.add(delta);}controls.update();renderFrame();}
function renderFrame(){if(drawing)drawing.render();else renderer.render(scene,camera);}
let contactMaterial;
function addContact(root,radius){if(!contactMaterial){const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(32,32,1,32,32,31);gradient.addColorStop(0,'rgba(54,47,36,.35)');gradient.addColorStop(.5,'rgba(54,47,36,.15)');gradient.addColorStop(1,'rgba(54,47,36,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);contactMaterial=new T.MeshBasicMaterial({map:new T.CanvasTexture(canvas),transparent:true,depthWrite:false});}const shadow=new T.Mesh(new T.PlaneGeometry(radius*2,radius*2),contactMaterial);shadow.rotation.x=-Math.PI/2;shadow.position.y=.004;root.add(shadow);}
async function init(){shell.hidden=false;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor('#f2eee5');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.VSMShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','역할을 수행하는 아홉 캐릭터의 입체 공간. 드래그로 회전하고 아래 버튼으로 확대할 수 있습니다.');renderer.domElement.setAttribute('role','img');
 scene=new T.Scene();camera=new T.PerspectiveCamera(36,1,.1,80);camera.up.set(0,1,0);controls=new OrbitControls(camera,renderer.domElement);controls.addEventListener('start',()=>following=false);controls.enableDamping=true;controls.dampingFactor=.09;controls.enablePan=false;controls.minPolarAngle=T.MathUtils.degToRad(15);controls.maxPolarAngle=T.MathUtils.degToRad(70);controls.minDistance=1.8;controls.maxDistance=28;controls.enableZoom=false;controls.touches.ONE=T.TOUCH.ROTATE;controls.touches.TWO=T.TOUCH.DOLLY_ROTATE;
 // Wheel zoom requires focus, leaving normal page scrolling available outside the space.
 host.tabIndex=0;host.setAttribute('aria-label','입체 공간 조작. 방향키 회전, 더하기와 빼기 확대 축소, Home 처음 시점');host.addEventListener('wheel',e=>{if(document.activeElement!==host)return;e.preventDefault();orbit(0,0,Math.exp(e.deltaY*.001));},{passive:false});host.addEventListener('pointerdown',()=>host.focus({preventScroll:true}));host.addEventListener('keydown',e=>{const map={ArrowLeft:[-.15,0,1],ArrowRight:[.15,0,1],ArrowUp:[0,-.12,1],ArrowDown:[0,.12,1],'+':[0,0,.88],'=':[0,0,.88],'-':[0,0,1.12]};if(map[e.key]){e.preventDefault();orbit(...map[e.key]);}if(e.key==='Home'){e.preventDefault();focusView();}});
 // Two-finger pinch is explicitly handled because wheel zoom is focus scoped.
 const touches=new Map();let pinch=0;host.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touches.set(e.pointerId,[e.clientX,e.clientY]);});host.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const [a,b]=[...touches.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)orbit(0,0,pinch/d);pinch=d;}});for(const type of ['pointerup','pointercancel'])host.addEventListener(type,e=>{touches.delete(e.pointerId);pinch=0;});
 scene.add(new T.HemisphereLight(0xfff8e8,0x87927d,1.8));const sun=new T.DirectionalLight(0xffedce,2.4);sun.position.set(-4,10,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:8,bottom:-8,near:.1,far:30});sun.shadow.radius=8;sun.shadow.blurSamples=16;sun.shadow.bias=-.0007;sun.shadow.normalBias=.02;scene.add(sun);const fill=new T.DirectionalLight(0xe5edff,.55);fill.position.set(6,5,-4);scene.add(fill);await prepareMaterials();makeWorld(scene);drawing=roomRendering(renderer,scene,camera);transferMesh=new T.Group();box(transferMesh,0,0,0,.38,.28,.035,'#7d9879',.013);box(transferMesh,0,.005,.021,.33,.23,.01,'#f3ead8',.006);transferMesh.visible=false;scene.add(transferMesh);focusView();resize();new ResizeObserver(resize).observe(host);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;last=performance.now();},{rootMargin:'100px'}).observe(host);raf=requestAnimationFrame(tick);
 await preload(n=>{status.textContent=`입체 캐릭터를 준비하고 있습니다 · ${n}/4`});roster.forEach(([key,name,h,x,z],id)=>{const a=actor(key,h);a.root.position.set(x,.03,z);scene.add(a.root);addContact(a.root,key==='howl'?.25:key==='dust'?.32:.38);const p={...a,key,name,h,id,round:0,age:0,speed:0,stage:'work'};people.push(p);assign(p);a.update(id*1.713,0,p.task.action,p.task.feeling,0,Infinity);const b=document.createElement('button');b.type='button';b.dataset.person=String(id);b.textContent=name;b.setAttribute('aria-pressed',String(id===0));b.addEventListener('click',()=>focusPerson(id));$('sim-roster').append(b);});
 ready=true;status.hidden=true;shell.classList.add('ready');$('world-image').hidden=shown;$('map-pins').hidden=shown||document.querySelector('[data-view="whole"]').getAttribute('aria-pressed')!=='true';if(shown)$('image-status').hidden=true;setPause(paused);updateLabel();window.dispatchEvent(new CustomEvent('simulation-ready'));
 const ray=new T.Raycaster(),pointer=new T.Vector2();let start;renderer.domElement.addEventListener('pointerdown',e=>start=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(people.map(p=>p.root),true);if(hits.length){let o=hits[0].object;while(o&&!people.some(p=>p.root===o))o=o.parent;const p=people.find(p=>p.root===o);if(p){selected=p.id;updateLabel();}}});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();graphicsLost=true;setPause(true);$('sim-pause').disabled=true;status.hidden=false;status.textContent='입체 화면 연결이 끊겼습니다. 복구를 기다리거나 공간 시안으로 볼 수 있습니다.';});
 renderer.domElement.addEventListener('webglcontextrestored',()=>{graphicsLost=false;renderer.setClearColor('#f2eee5',drawing?0:1);$('sim-pause').disabled=false;status.hidden=false;status.textContent='입체 화면이 돌아왔습니다. 움직임 재생으로 이어갈 수 있습니다.';resize();});
 }catch(error){status.hidden=false;status.textContent='입체 공간을 불러오지 못했습니다. 공간 시안으로 볼 수 있습니다.';console.error('Space loading failed',error);if(shown)$('sim-mode').click();}}
for(const b of document.querySelectorAll('[data-performance]'))b.addEventListener('click',()=>playScene(b.dataset.performance));
$('sim-pause').addEventListener('click',()=>setPause(!paused));$('sim-auto').addEventListener('click',()=>{auto=!auto;phaseAge=0;$('sim-auto').setAttribute('aria-pressed',String(auto));$('sim-auto').textContent=auto?'단계 자동 진행 끄기':'단계 자동 진행';});
for(const b of document.querySelectorAll('[data-camera]'))b.addEventListener('click',()=>{if(!controls)return;const action=b.dataset.camera,steps={left:[-.2,0,1],right:[.2,0,1],up:[0,-.14,1],down:[0,.14,1],in:[0,0,.82],out:[0,0,1.22]};following=false;if(action==='reset')focusView();else orbit(...steps[action]);});
$('sim-mode').addEventListener('click',()=>{shown=!shown;shell.hidden=!shown;$('world-image').hidden=shown;$('map-pins').hidden=shown||document.querySelector('[data-view="whole"]').getAttribute('aria-pressed')!=='true';$('sim-mode').textContent=shown?'공간 시안 보기':'입체 공간 보기';$('sim-mode').setAttribute('aria-pressed',String(!shown));if(shown)resize();});
window.addEventListener('space-view',e=>{if(controls)focusView(e.detail);if(shown)$('map-pins').hidden=true;});window.addEventListener('space-phase',e=>setPhase(e.detail.step,e.detail.wait));window.addEventListener('space-area',e=>{if(controls)focusView(e.detail);});
reduced.addEventListener('change',e=>{if(e.matches)setPause(true);});document.addEventListener('visibilitychange',()=>last=performance.now());window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));window.addEventListener('pageshow',e=>{if(e.persisted){last=performance.now();raf=requestAnimationFrame(tick);}});
window.agentSpace={THREE:T,get ready(){return ready},get paused(){return paused},get phase(){return phase},get time(){return time},get transfer(){return transferProgress},people,obstacles,blocked,renderFrame,orbit,playScene,focusView,focusPerson,setPhase,setPause,get camera(){return camera},get controls(){return controls},get scene(){return scene},get renderer(){return renderer},snapshot(){return {ready,paused,phase,time,shown,polar:controls?.getPolarAngle(),distance:controls?.getDistance(),camera:camera?.position.toArray(),target:controls?.target.toArray(),agents:people.map(p=>({id:p.id,key:p.key,x:p.root.position.x,z:p.root.position.z,stage:p.stage,action:p.action,task:p.task.action,path:p.path.length}))}}};
init();
