const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = n => String(n).padStart(2,'0');
const image = id => `./assets/object-${num(id)}.webp`;
const APP = 'https://euna-source.github.io/public-pages/meonji-collect/';
const KEY = 'meonji.archive.design.v1';
const AXES = ['색의 존재감','형태의 변주','질감','간결함','실용성','시간의 흔적'];
const originals = [
 {id:1,title:'코발트 유리컵',desc:'빛을 받으면 더 선명해지는 파랑. 단순한 원통과 투명한 재질.',labels:['color','daily'],axes:[0,2,3,4]},
 {id:2,title:'고리 모양 촛대',desc:'두 개의 선이 교차하는 크롬 촛대. 차가운 금속과 둥근 형태.',labels:['shape','daily'],axes:[1,2,3]},
 {id:3,title:'노란 스테이플러',desc:'익숙한 사무용품에 한 가지 선명한 색. 책상에 남겨두고 싶은 물건.',labels:['color','daily'],axes:[0,3,4]},
 {id:4,title:'분홍 머그',desc:'매트한 표면과 넉넉한 손잡이. 자주 손이 갈 것 같은 잔.',labels:['color','daily'],axes:[0,2,3,4]},
 {id:5,title:'초록 리넨',desc:'접힌 자국과 짜임이 그대로 보이는 천. 부드러운 색과 거친 촉감.',labels:['texture','daily'],axes:[0,2,4,5]},
 {id:6,title:'스틸 가위',desc:'기능을 따라 남은 모양. 날과 손잡이가 같은 재료로 이어지는 도구.',labels:['shape','daily'],axes:[1,2,3,4,5]},
 {id:7,title:'각진 파란 화병',desc:'둥근 입구와 각진 몸통. 작은 면마다 빛의 색이 달라진다.',labels:['color','shape'],axes:[0,1,2]},
 {id:8,title:'아무것도 쓰지 않은 노트',desc:'크림색 종이와 얇은 스프링. 아직 채워지지 않은 페이지.',labels:['texture','daily'],axes:[2,3,4]},
 {id:9,title:'실버 필름 카메라',desc:'손에 들어오는 작은 크기. 사진 한 장씩 기다리던 시간을 닮은 도구.',labels:['texture','daily'],axes:[2,4,5]},
 {id:10,title:'호피무늬 안경',desc:'투명한 갈색 프레임 속 불규칙한 무늬. 매일 쓰는 작은 물건.',labels:['texture','daily'],axes:[0,2,4,5]},
 {id:11,title:'물결치는 빨간 초',desc:'불을 켜기 전에도 조각 같은 초. 반복되는 곡선과 선명한 빨강.',labels:['color','shape'],axes:[0,1,2]},
 {id:12,title:'초록 소용돌이 문진',desc:'맑은 유리 속에 멈춘 초록 선. 종이를 누르는 작고 묵직한 구체.',labels:['shape','texture'],axes:[0,1,2,4]},
];
originals.push({id:13,title:'오래 남는 한 문장',kind:'text',sample:true,quote:'좋아하는 것을 모으다 보면,\n무엇을 남기고 싶은지도 알게 된다.',desc:'문장을 편지지에 남기는 예시입니다.',book:'직접 쓴 예시 문장',author:'',page:'',memo:'아직 비어 있는 서랍에 첫 문장을 넣으며.',labels:['letters','daily'],axes:[]});
const labels = {all:{name:'모든 수집물',en:'Collected things',color:'#e2e1d5',desc:'마음이 머문 물건과 문장을 한 장씩 펼쳐봅니다.'},daily:{name:'매일 곁에',en:'Everyday companions',color:'#b7c9bf',desc:'자주 손이 가고, 오래 곁에 두고 싶은 것들.'},color:{name:'색을 모으다',en:'A little color',color:'#e6c6cb',desc:'작은 물건 하나로 달라지는 방의 표정.'},shape:{name:'낯선 모양',en:'Unexpected forms',color:'#d6e76b',desc:'익숙한 쓰임에 조금 다른 모양.'},texture:{name:'손끝의 감각',en:'Material memories',color:'#d9cfb8',desc:'표면과 재료, 그 위에 남은 시간.'}};
labels.letters={name:'남겨둔 문장',en:'Words to keep',color:'#f7f5ee',desc:'책에서 만난 문장과, 그때의 나를 함께 남겨요.'};
Object.values(labels).forEach(l=>l.color='#eee');labels.daily.color='#191919';labels.color.color='#fff';labels.shape.color='#d6d6d6';
const drawers=[{name:'일상에서 발견',en:'Everyday discoveries',ids:['daily','color','shape']},{name:'재료와 장면',en:'Materials & memories',ids:['letters','texture','shape']},{name:'모두 펼쳐보기',en:'The complete archive',ids:['all','daily','texture']}];
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
let cards=originals.map(c=>({...c,...(saved.cards?.find?.(x=>x.id===c.id)||{}),id:c.id,title:c.title,desc:c.desc,axes:c.axes}));
cards=cards.map(c=>({...c,labels:Array.isArray(c.labels)?c.labels.filter(x=>x!=='all'&&labels[x]):[],verdict:['like','no'].includes(c.verdict)?c.verdict:null,reason:typeof c.reason==='string'?c.reason:''}));
if(Array.isArray(saved.letters)) for(const x of saved.letters.slice(0,1000)){if(!Number.isSafeInteger(x.id)||x.id<1000||typeof x.quote!=='string')continue;cards.push({id:x.id,kind:'text',title:String(x.title||'남겨둔 문장').slice(0,80),quote:x.quote.slice(0,8000),book:String(x.book||'').slice(0,200),author:String(x.author||'').slice(0,100),page:String(x.page||'').slice(0,30),memo:String(x.memo||'').slice(0,2000),desc:'직접 남긴 글귀',labels:Array.isArray(x.labels)?x.labels.filter(l=>labels[l]&&l!=='all'):['letters'],axes:[],verdict:['like','no'].includes(x.verdict)?x.verdict:null,reason:String(x.reason||'').slice(0,300)});}
let criterion=typeof saved.criterion==='string'?saved.criterion:'';
let mode=['tray','specimen','collage'].includes(saved.mode)?saved.mode:'specimen';
let drawerIndex=0,query='',lastUndo=null,deckId=null,toastTimer,reasonDrafts={},criterionDraft=null,openedItem=null,openTrigger=null,layerScroll=0,composePinned=false,compositionActive=false,lastCompositionAt=0,resumeQuoteFocus=false;
function persist(){try{localStorage.setItem(KEY,JSON.stringify({cards:cards.map(({id,labels,verdict,reason})=>({id,labels,verdict,reason})),criterion,mode,letters:cards.filter(c=>c.kind==='text'&&!c.sample)}));return true}catch{toast('저장하지 못했어요. 입력은 그대로 두었어요.');return false}}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function source(c){return [c.book,c.author,c.page&&'p. '+c.page].filter(Boolean).join(' · ')||'출처를 남기지 않은 문장'}
function paper(c,mini=false){return `<div class="letter-paper ${mini?'mini':''}"><span class="letter-date mono">a note to myself</span><span class="letter-mark" aria-hidden="true">“</span><blockquote>${esc(c.quote)}</blockquote><cite>${esc(source(c))}</cite>${!mini&&c.memo?`<div class="letter-memo"><span>그때의 기록</span><p>${esc(c.memo)}</p></div>`:''}</div>`}
function selected(id){return cards.filter(c=>id==='all'||c.labels.includes(id))}
function state(){const [route='home',id='all']=location.hash.slice(1).split('/');return{route:['home','collection','deck','taste'].includes(route)?route:'home',id:labels[id]?id:'all'}}
function redraw(fn,focus=false){const change=()=>{fn();if(focus)$('#main').focus({preventScroll:true})};change()}
function render(){
 const s=state(),composer=$('#composer');
 $('#compose-home').append(composer);
 document.querySelectorAll('.topbar nav a').forEach(a=>{if(a.hash.split('/')[0]==='#'+s.route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 $('#main').innerHTML=s.route==='home'?home():s.route==='collection'?collection(s.id):s.route==='deck'?deck():taste();
 if($('#composer-slot'))$('#composer-slot').append(composer);
 if(s.route==='collection'&&s.id==='letters'){composer.hidden=false;setComposerType('letter')}
 else composer.hidden=!composePinned;
 bind(s);
}
function folder(id,index){const l=labels[id],list=selected(id);return `<button class="folder ${id==='daily'?'folder-dark':''}" data-folder="${id}" aria-label="${l.name} 파일 열기" style="--folder-color:${l.color}"><div class="folder-preview" aria-hidden="true">${list.slice(0,2).map(c=>c.kind==='text'?paper(c,true):`<img src="${image(c.id)}" alt="">`).join('')}</div><div class="folder-cover"><span class="mono">FILE ${num(index+1)} / ${num(list.length)} ITEMS</span><h3>${l.name}</h3><p>${l.en}</p><span class="open-mark" aria-hidden="true">↗</span></div></button>`}
function home(){const d=drawers[drawerIndex];return `<div class="page-heading"><div><h1>나의 서랍</h1><p>마음이 머문 것들을, 다시 꺼내 보는 곳.</p></div><span class="serial archive-wordmark">The archive<span class="wordmark-dot">.</span></span></div><div class="archive-layout"><aside class="cabinet" aria-label="서랍 선택"><div class="cabinet-note mono"><span>Cabinet 01</span><span>3 drawers</span></div>${drawers.map((d,i)=>`<button class="drawer ${i===drawerIndex?'active':''}" data-drawer="${i}" aria-pressed="${i===drawerIndex}"><span class="drawer-label">${d.name}<small>${num(i+1)}</small></span><span class="handle" aria-hidden="true"></span></button>`).join('')}<p class="cabinet-foot"><span class="line"></span>한 물건이 여러 파일에 있어도<br>내가 남긴 마음은 하나예요.</p></aside><section aria-label="${d.name}의 파일"><div class="shelf-head"><h2>${d.en}</h2><span>서랍 ${num(drawerIndex+1)} · 파일 3개</span></div><div class="folder-shelf">${d.ids.map(folder).join('')}</div><div class="shelf-note"><span>파일을 열어 수집물을 펼쳐보세요.</span><span>${cards.length} originals / multiple perspectives</span></div><div class="archive-bottom"><button class="photo-drawer" data-folder="all" aria-label="칸막이 서랍으로 모든 수집물 보기"><img src="./assets/drawer.webp" alt="물건과 종이 조각이 칸마다 담긴 크림색 서랍"><span>서랍 안을 한눈에 ↗</span></button><div class="index-preview"><h3>Index of little things</h3>${['letters','shape','texture'].map((id,i)=>`<a class="index-row" href="#collection/${id}"><span>${num(i+1)}</span>${labels[id].name}<span>${num(selected(id).length)} ↗</span></a>`).join('')}<a class="index-row" href="#taste"><span>↳</span>나의 감각을 읽는 중<span>${cards.filter(c=>c.verdict).length}/${cards.length}</span></a></div></div></section></div>`}
function collection(id){const l=labels[id];return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>${l.name}</span></div><div class="collection-header"><div><h1>${l.name}</h1><p class="subtitle">${l.desc}</p></div><span class="collection-serial">${num(selected(id).length)}</span></div><div class="collection-tools"><nav class="label-tabs" aria-label="라벨 파일">${Object.entries(labels).map(([key,l])=>`<a href="#collection/${key}" ${key===id?'aria-current="page"':''}>${l.name}</a>`).join('')}</nav>${id==='letters'?'<button class="primary small" data-write-letter>＋ 글귀 남기기</button>':''}<div class="view-modes" role="group" aria-label="모음집 보기">${[['specimen','도감'],['tray','칸막이'],['collage','콜라주']].map(([m,t])=>`<button data-mode="${m}" aria-pressed="${mode===m}">${t}</button>`).join('')}</div></div><label class="hint" for="collection-search">이 파일에서 찾기</label><input class="collection-search" id="collection-search" type="search" placeholder="이름·문장·책 제목으로 찾기" value="${esc(query)}"><div id="composer-slot"></div><div id="collection-objects">${objects(id)}</div><div class="catalog-foot"><span>${l.en} · 같은 물건의 선택과 이유는 모든 파일에 함께 남아요.</span><span>Meonji / ${new Date().getFullYear()}</span></div>`}
function objects(id){
 const list=selected(id).filter(c=>c.title.includes(query)||c.desc.includes(query)||(c.quote||'').includes(query)||(c.book||'').includes(query));
 if(!list.length)return `<div class="empty"><h2>아직 이곳에는 없어요.</h2><p>다른 이름으로 찾거나 다른 파일을 펼쳐보세요.</p><button class="link" id="search-reset">검색 지우기</button></div>`;
 return `<div class="object-grid ${mode}">${list.map(c=>`<article class="object" data-card-id="${c.id}">
 <button class="object-photo ${c.kind==='text'?'quote-photo':''}" data-item="${c.id}" aria-label="${esc(c.title)} 크게 보기">${c.kind==='text'?paper(c,true):`<img src="${image(c.id)}" alt="${esc(c.title)}" loading="lazy">`}<span class="enlarge-mark" aria-hidden="true">↗</span></button>
 <div class="object-meta"><span class="number">${c.kind==='text'?'¶':num(c.id)}</span><div><h3>${esc(c.title)}</h3><p class="object-description">${esc(c.kind==='text'?source(c):c.desc)}</p><small>${c.labels.map(x=>labels[x].name).join(' · ')}</small></div></div>
 ${c.kind==='text'&&c.memo?`<p class="object-reflection">${esc(c.memo)}</p>`:''}
 <form class="inline-note" data-note="${c.id}"><label for="reason-${c.id}">이유 한 줄 <span>(선택)</span></label><div class="note-entry"><input id="reason-${c.id}" maxlength="300" aria-describedby="note-status-${c.id}" placeholder="바로 적고 Enter" value="${esc(reasonDrafts[c.id]??c.reason??'')}"><button type="submit" aria-label="${esc(c.title)} 이유 저장">↵</button></div><div class="inline-actions"><div class="inline-choices" role="group" aria-label="${esc(c.title)} 내 선택"><button type="button" data-inline-judge="no" aria-pressed="${c.verdict==='no'}" aria-label="${esc(c.title)} 아니요">X</button><button type="button" data-inline-judge="like" aria-pressed="${c.verdict==='like'}" aria-label="${esc(c.title)} 좋아요">O</button></div><span class="note-status" id="note-status-${c.id}" role="status">${reasonDrafts[c.id]!==undefined?'작성 중':c.verdict?(c.verdict==='like'?'O 좋아요':'X 아니요'):c.reason?'기록됨':''}</span></div></form>
 ${c.verdict?`<span class="verdict-stamp" aria-hidden="true">${c.verdict==='like'?'O':'X'}</span>`:''}</article>`).join('')}</div>${mode==='tray'?'<div class="tray-front"><span class="handle" aria-hidden="true"></span><small>나의 작은 수집물</small></div>':''}`;
}
function bind(s){document.querySelectorAll('[data-write-letter]').forEach(b=>b.onclick=()=>openComposer('letter'));document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>{drawerIndex=+b.dataset.drawer;redraw(()=>{render();document.querySelector(`[data-drawer="${drawerIndex}"]`)?.focus()})});document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{query='';location.hash='collection/'+b.dataset.folder});bindObjects();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;persist();redraw(()=>{render();document.querySelector(`[data-mode="${mode}"]`)?.focus()})});if(s.route==='collection'){$('#collection-search').oninput=e=>{query=e.target.value;$('#collection-objects').innerHTML=objects(s.id);bindObjects()}}if(s.route==='deck')bindDeck();if(s.route==='taste'){$('#criterion').oninput=e=>{criterionDraft=e.target.value;$('#criterion-status').textContent='작성 중'};$('#criteria-form').onsubmit=e=>{e.preventDefault();const old=criterion;criterion=$('#criterion').value.trim();if(persist()){criterionDraft=null;$('#criterion-status').textContent='저장됨';toast('내 기준을 남겼어요.')}else{criterion=old;$('#criterion-status').textContent='저장하지 못했어요. 다시 Enter로 저장해 주세요.'}};document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>openItem(+b.dataset.evidence))}}
function bindObjects(){
 document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>openItem(+b.dataset.item,b));
 document.querySelectorAll('[data-note]').forEach(form=>{
  const id=+form.dataset.note,input=form.querySelector('input');
  input.oninput=()=>{reasonDrafts[id]=input.value;form.querySelector('.note-status').textContent='작성 중'};
  form.onsubmit=e=>{e.preventDefault();if(isComposing())return;saveReason(id,input.value,form.querySelector('.note-status'))};
  form.querySelectorAll('[data-inline-judge]').forEach(b=>b.onclick=()=>{if(judge(id,b.dataset.inlineJudge,input.value))document.querySelector(`[data-note="${id}"] [data-inline-judge="${b.dataset.inlineJudge}"]`)?.focus({preventScroll:true});else form.querySelector('.note-status').textContent='저장하지 못했어요. 다시 시도해 주세요.'});
 });
 if($('#search-reset'))$('#search-reset').onclick=()=>{query='';render();$('#collection-search').focus()};
}
function saveReason(id,value,status){const c=cards.find(c=>c.id===id),old=c.reason;c.reason=value.trim();if(!persist()){c.reason=old;reasonDrafts[id]=value;status.textContent='저장하지 못했어요. 다시 Enter로 저장해 주세요.';return false}delete reasonDrafts[id];status.textContent='저장됨';document.querySelectorAll(`[data-note="${id}"] input`).forEach(el=>el.value=c.reason);toast('이유를 남겼어요. O/X는 따로 고를 수 있어요.');return true}

function openItem(id,trigger){openedItem=id;if(trigger)openTrigger=trigger;const c=cards.find(x=>x.id===id);if(!c)return;$('#item-content').innerHTML=`<button class="close" data-close="item-dialog" aria-label="닫기">×</button><div class="item-layout"><div class="item-visual ${c.kind==='text'?'letter-visual':''}">${c.kind==='text'?paper(c):`<img src="${image(c.id)}" alt="${esc(c.title)}">`}</div><div class="item-detail"><span class="mono">${c.kind==='text'?'LETTER':'OBJECT '+num(c.id)} · ${c.kind==='text'&&!c.sample?'내 기록':'예시 수집물'}</span><h2 id="item-title">${esc(c.title)}</h2><p>${c.kind==='text'?esc(source(c)):c.desc}</p><div class="tag-list">${c.labels.map(id=>`<a href="#collection/${id}" data-label-link>${labels[id].name} ↗</a>`).join('')}</div><label for="item-reason">이유 한 줄 <span class="hint">(선택)</span></label><input id="item-reason" maxlength="300" aria-describedby="item-note-status" placeholder="마음이 움직인 이유가 있다면" value="${esc(reasonDrafts[id]??c.reason??'')}"><p id="item-note-status" class="hint" role="status">Enter로 이유 저장</p><div class="decision-buttons"><button data-judge="no"><strong>X</strong>아니요</button><button data-judge="like"><strong>O</strong>좋아요</button></div><p class="hint" id="item-verdict">${c.verdict?`내 선택: ${c.verdict==='like'?'O 좋아요':'X 아니요'}`:'아직 고르지 않았어요.'}</p><div class="membership"><label for="label-select">다른 파일에도 넣기</label><select id="label-select" aria-label="추가할 라벨"><option value="">라벨 선택</option>${Object.entries(labels).filter(([id])=>id!=='all'&&!c.labels.includes(id)).map(([id,l])=>`<option value="${id}">${l.name}</option>`).join('')}</select><button id="attach-label">선택한 파일에 함께 넣기 ＋</button><span class="hint">원본 ${c.kind==='text'?'글귀':num(c.id)} · 파일 ${c.labels.length}개에 연결</span></div></div></div>`;
 const dialog=$('#item-dialog');if(!dialog.open){layerScroll=window.scrollY;dialog.showModal();document.body.classList.add('layer-open');dialog.scrollTop=0;$('#item-content .close').focus({preventScroll:true})}$('#item-reason').oninput=e=>{reasonDrafts[id]=e.target.value;$('#item-note-status').textContent='작성 중'};$('#item-reason').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing&&!isComposing()&&e.keyCode!==229){e.preventDefault();saveReason(id,e.target.value,$('#item-note-status'))}};$('#item-content [data-close]').onclick=()=>dialog.close();$('#item-content').querySelectorAll('[data-label-link]').forEach(a=>a.onclick=()=>{query='';dialog.close()});$('#item-content').querySelectorAll('[data-judge]').forEach(b=>b.onclick=()=>{if(judge(c.id,b.dataset.judge,$('#item-reason').value)){openItem(id);$('#item-reason').focus()}else $('#item-note-status').textContent='저장하지 못했어요. 다시 시도해 주세요.'});$('#attach-label').onclick=()=>{const label=$('#label-select').value;if(!label)return toast('넣을 파일을 골라 주세요.');c.labels.push(label);if(!persist()){c.labels.pop();return}render();openItem(id);toast('원본 하나를 두 파일에서 볼 수 있어요.');};}
function judge(id,verdict,reason){const c=cards.find(c=>c.id===id),previous={verdict:c.verdict,reason:c.reason};c.verdict=verdict;c.reason=reason.trim();if(!persist()){Object.assign(c,previous);reasonDrafts[id]=reason;return false}lastUndo={id,...previous,draft:reason};delete reasonDrafts[id];render();if(state().route==='deck')$(verdict==='like'?'#choose-like':'#choose-no')?.focus();toast(`${verdict==='like'?'O':'X'} 선택이 연결된 파일에 함께 남았어요.`);return true}
function deck(){const pending=cards.filter(c=>!c.verdict);const c=pending.find(c=>c.id===deckId)||pending[0];deckId=c?.id;const done=cards.filter(c=>c.verdict).length;return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>취향 고르기</span></div><div class="page-heading"><div><h1>마음에 남나요?</h1><p>이유는 떠오를 때만. 먼저 내 감각으로 골라보세요.</p></div><span class="mono">${num(done)} / ${cards.length} CHOICES</span></div>${!c?`<div class="empty"><h2>선택이 한 바퀴 모였어요.</h2><p>고른 물건을 다시 펼치거나 감각 분포를 확인해 보세요.</p><a class="primary" href="#taste">나의 감각 보기</a>${lastUndo?'<button id="undo" class="link" style="margin-left:20px">되돌리기</button>':''}</div>`:`<div class="deck-layout"><article class="paper-sheet" id="deck-card" data-card="${c.id}"><span class="mono">${c.kind==='text'?'LETTER':'OBJECT '+num(c.id)} / YOUR CHOICE</span><div class="deck-photo ${c.kind==='text'?'quote-photo':''}">${c.kind==='text'?paper(c):`<img src="${image(c.id)}" alt="${esc(c.title)}">`}</div><div class="sheet-caption"><h2>${esc(c.title)}</h2><span class="mono">${c.kind==='text'?'¶':num(c.id)}</span></div></article><div class="deck-info"><h2>A little instinct.</h2><p>${c.desc}</p><div class="progress-track" aria-label="${done}개 판정 완료"><span style="width:${done/cards.length*100}%"></span></div><label for="deck-reason">이유 한 줄 <span class="hint">(선택)</span></label><input id="deck-reason" maxlength="300" placeholder="적지 않아도 괜찮아요" value="${esc(reasonDrafts[c.id]??c.reason??'')}"><p id="deck-note-status" class="hint" role="status">Enter로 이유만 먼저 남길 수 있어요.</p><div class="decision-buttons"><button id="choose-no"><strong>X</strong>아니요</button><button id="choose-like"><strong>O</strong>좋아요</button></div><div class="deck-bottom"><button id="undo" ${lastUndo?'':'disabled'}>되돌리기</button><button id="skip-card">지금은 모르겠어요 →</button></div><p class="hint">← X · O → &nbsp; 카드도 좌우로 넘길 수 있어요.</p></div></div>`}`}
function bindDeck(){const c=cards.find(c=>c.id===deckId);if($('#undo'))$('#undo').onclick=()=>{if(!lastUndo)return;const x=cards.find(c=>c.id===lastUndo.id);x.verdict=lastUndo.verdict;x.reason=lastUndo.reason;reasonDrafts[x.id]=lastUndo.draft;deckId=x.id;lastUndo=null;persist();render();toast('직전 선택을 되돌렸어요.')};if(!c||!$('#deck-reason'))return;$('#deck-reason').oninput=e=>reasonDrafts[c.id]=e.target.value;$('#deck-reason').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing&&!isComposing()&&e.keyCode!==229){e.preventDefault();saveReason(c.id,e.target.value,$('#deck-note-status'))}};$('#choose-no').onclick=()=>judge(c.id,'no',$('#deck-reason').value);$('#choose-like').onclick=()=>judge(c.id,'like',$('#deck-reason').value);$('#skip-card').onclick=()=>{const pending=cards.filter(c=>!c.verdict);const i=pending.findIndex(x=>x.id===c.id);deckId=pending[(i+1)%pending.length]?.id;render();toast('판정하지 않고 다음 물건으로 넘겼어요.')};const el=$('#deck-card');el.style.touchAction='pan-y';let start;el.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId)};el.onpointerup=e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.3)judge(c.id,dx>0?'like':'no',$('#deck-reason').value)};el.onpointercancel=()=>start=null;}
function profile(){return AXES.map((name,i)=>{const evidence=cards.filter(c=>c.axes.includes(i)&&c.verdict);const likes=evidence.filter(c=>c.verdict==='like').length;return{name,evidence,score:evidence.length>=3?Math.round(likes/evidence.length*100):null}})}
function radar(axes){const center=[210,160],r=105;const point=(i,v)=>{const a=-Math.PI/2+i*Math.PI/3;return[center[0]+Math.cos(a)*r*v,center[1]+Math.sin(a)*r*v]};const pts=v=>axes.map((_,i)=>point(i,v).join(',')).join(' ');return `<svg class="radar" viewBox="0 0 420 325" role="img" aria-label="선택으로 쌓이는 여섯 방향 감각 분포. 근거 3개 미만은 미평가.">${[.25,.5,.75,1].map(v=>`<polygon points="${pts(v)}" fill="none" stroke="#d9d9d9" stroke-width="1"/>`).join('')}${axes.map((a,i)=>{const p=point(i,1),t=point(i,1.29);return `<path d="M210 160 L${p.join(' ')}" stroke="#d9d9d9"/><text x="${t[0]}" y="${t[1]}" text-anchor="middle">${a.name}</text>`}).join('')}${axes.every(a=>a.score!==null)?`<polygon class="radar-value" points="${axes.map((a,i)=>point(i,a.score/100).join(',')).join(' ')}" fill="#14141420" stroke="#141414" stroke-width="2"/>`:''}${axes.map((a,i)=>{if(a.score===null)return '';const p=point(i,a.score/100);return `<circle cx="${p[0]}" cy="${p[1]}" r="4" fill="#141414"/>`}).join('')}<circle cx="210" cy="160" r="2" fill="#606060"/></svg>`}
function taste(){const axes=profile(),judged=cards.filter(c=>c.verdict).length,known=axes.filter(a=>a.score!==null).sort((a,b)=>b.score-a.score);const strong=known.filter(a=>a.score>=60).slice(0,2);const conclusion=strong.length?`${strong.map(a=>a.name).join('과 ')}에서 O 선택이 더 많았어요. 아직 예시 몇 개로 본 초기 관찰이에요.`:judged?`아직 한 방향으로 말하기엔 선택이 더 필요해요.`:'아직 빈 도면이에요. 내 선택이 쌓이면 윤곽이 나타나요.';return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>나의 감각</span></div><div class="page-heading"><div><h1>내가 좋아하는 방향</h1><p>기준은 내 말로 남기고, 선택의 결은 여러 방향으로 읽어요.</p></div><span class="serial">A portrait in choices.</span></div><div class="taste-layout"><section class="taste-input"><h2>나의 기준</h2><form id="criteria-form"><label for="criterion">좋아하는 것, 남겨두고 싶은 것을 자유롭게</label><textarea id="criterion" maxlength="1000" aria-describedby="criterion-status" placeholder="예를 들면, 매일 쓰는 물건에도 조금 낯선 모양이 있으면 좋겠어. 오래 쓸 수 있고 손에 닿는 느낌이 좋은 것.">${esc(criterionDraft??criterion)}</textarea><p class="hint" id="criterion-status" role="status">Enter 저장 · Shift+Enter 줄바꿈</p><button class="primary" type="submit">내 기준 남기기 ↵</button></form><p class="hint">여기에 한 번만 적어요. 항목을 나누는 일은 결과를 볼 때만 해요.</p><p class="hint">체험판은 예시 물건의 특징과 직접 고른 O/X로 분포를 계산해요. 문장의 자동 해석과 실제 내 수집물 분석은 아직 연결하지 않았어요.</p><a class="index-row" href="#deck">계속 취향 고르기 <span>${judged}/${cards.length} →</span></a></section><section class="taste-result" aria-label="감각 분석 결과"><header><h2>My sensibility</h2><span class="mono">${num(judged)} CHOICES</span></header>${radar(axes)}<p class="taste-summary">${conclusion}</p><div class="axis-list">${axes.map(a=>`<details><summary>${a.name}<b>${a.score===null?'미평가':a.score+'%'}</b></summary><p>관련 선택 ${a.evidence.length}개 · O ${a.evidence.filter(c=>c.verdict==='like').length}개</p><ul>${a.evidence.map(c=>`<li><button class="link" data-evidence="${c.id}">${esc(c.title)}</button> · ${c.verdict==='like'?'O':'X'}${c.reason?' · '+esc(c.reason):''}</li>`).join('')||'<li>이 축에 연결된 선택이 아직 없어요.</li>'}</ul></details>`).join('')}</div><p class="hint" style="margin-top:20px">축마다 선택 3개부터 O 비율을 표시해요. 빈 축은 0점이 아니에요. 예시 기반 탐색이며 성격·능력 점수가 아니에요.</p></section></div>`}
function setComposerType(type){document.querySelectorAll('[data-compose]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.compose===type)));$('#letter-form').hidden=type!=='letter';$('#capture-form').hidden=type!=='url'}
function openComposer(type='letter'){composePinned=true;$('#composer').hidden=false;setComposerType(type);$(type==='letter'?'#letter-quote':'#source-url').focus();}
function isComposing(){return compositionActive||Date.now()-lastCompositionAt<80}
document.addEventListener('compositionstart',()=>compositionActive=true);
document.addEventListener('compositionend',()=>{compositionActive=false;lastCompositionAt=Date.now()});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'||!e.target.matches('input,textarea'))return;if(e.isComposing||e.keyCode===229||isComposing())return;if(e.shiftKey&&e.target.matches('textarea'))return;const form=e.target.form;if(form&&['letter-form','criteria-form','capture-form'].includes(form.id)){e.preventDefault();form.requestSubmit()}});
$('#item-dialog').addEventListener('close',()=>{document.body.classList.remove('layer-open');const card=cards.find(c=>c.id===openedItem),form=document.querySelector(`[data-note="${openedItem}"]`);if(form&&card){form.querySelector('input').value=reasonDrafts[openedItem]??card.reason??'';form.querySelector('.note-status').textContent=reasonDrafts[openedItem]!==undefined?'작성 중':card.reason?'기록됨':''}const target=document.querySelector(`[data-item="${openedItem}"]`)||(openTrigger?.isConnected?openTrigger:$('#main'));target?.focus({preventScroll:true});window.scrollTo({top:layerScroll,behavior:'instant'})});
$('#item-dialog').addEventListener('click',e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close()});
$('#letter-form').onsubmit=e=>{e.preventDefault();if(isComposing())return;const quote=$('#letter-quote').value.trim();if(!quote){$('#letter-status').textContent='남길 문장을 적어 주세요.';return}const c={id:Math.max(Date.now(),...cards.map(c=>c.id+1)),kind:'text',title:quote.split('\n')[0].slice(0,40),quote,book:$('#letter-book').value.trim(),author:$('#letter-author').value.trim(),page:$('#letter-page').value.trim(),memo:$('#letter-memo').value.trim(),desc:'직접 남긴 글귀',labels:['letters'],axes:[],verdict:null,reason:''};cards.push(c);if(persist()){e.target.reset();query='';$('#letter-status').textContent='저장됨 · 아래 문장 파일에 남겼어요.';composePinned=false;resumeQuoteFocus=location.hash!=='#collection/letters';location.hash='collection/letters';render();$('#letter-quote').focus({preventScroll:true});toast('문장을 남겼어요. 계속 적어도 좋아요.')}else{cards.pop();$('#letter-status').textContent='저장하지 못했어요. 입력은 그대로 있어요. 다시 Enter로 저장해 주세요.'}};
$('#actual-app').href=APP+'#/list';$('#add-open').onclick=()=>openComposer();$('#composer-close').onclick=()=>{composePinned=false;$('#composer').hidden=true;$('#add-open').focus({preventScroll:true})};document.querySelectorAll('[data-compose]').forEach(b=>b.onclick=()=>setComposerType(b.dataset.compose));
$('#capture-form').onsubmit=e=>{e.preventDefault();if(isComposing())return;const url=$('#source-url').value;const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))return toast('웹페이지 주소를 넣어 주세요.');location.href=APP+'#/add?'+new URLSearchParams({url})};
document.addEventListener('keydown',e=>{if(e.defaultPrevented||state().route!=='deck'||document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();$(e.key==='ArrowRight'?'#choose-like':'#choose-no')?.click()}});
window.addEventListener('hashchange',()=>{query='';document.querySelectorAll('dialog[open]').forEach(d=>d.close());redraw(render,!resumeQuoteFocus);if(resumeQuoteFocus){$('#letter-quote').focus({preventScroll:true});resumeQuoteFocus=false}else window.scrollTo({top:0,behavior:'instant'})});
window.addEventListener('storage',e=>{if(e.key===KEY)toast('다른 창에서 변경됐어요. 이 창의 입력을 마친 뒤 새로고침해 주세요.')});
render();
