const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = n => String(n).padStart(2,'0');
const image = id => `./assets/object-${num(id)}.webp`;
const APP = 'https://euna-source.github.io/public-pages/meonji-collect/';
const KEY = 'meonji.archive.design.v1';
const AXES = ['색의 존재감','형태의 변주','질감','간결함','실용성','시간의 흔적'];
const originals = [
 {id:1,title:'코발트 유리컵',desc:'빛을 받으면 더 선명해지는 파랑. 단순한 원통과 투명한 재질.',labels:['color','daily'],axes:[0,2,3,4]},
 {id:2,title:'고리 모양 촛대',desc:'두 개의 선이 교차하는 크롬 촛대. 차가운 금속과 둥근 형태.',labels:['shape','daily'],axes:[1,2,3]},
 {id:3,title:'노란 스테이플러',desc:'익숙한 사무용품에 한 가지 선명한 색. 책상에 남겨두고 싶은 물건.',labels:['color','daily'],axes:[0,3,4]},
 {id:4,title:'분홍 머그',desc:'매트한 표면과 넉넉한 손잡이. 자주 손이 갈 것 같은 잔.',labels:['color','daily'],axes:[0,2,3,4]},
 {id:5,title:'초록 리넨',desc:'접힌 자국과 짜임이 그대로 보이는 천. 부드러운 색과 거친 촉감.',labels:['texture','daily'],axes:[0,2,4,5]},
 {id:6,title:'스틸 가위',desc:'기능을 따라 남은 모양. 날과 손잡이가 같은 재료로 이어지는 도구.',labels:['shape','daily'],axes:[1,2,3,4,5]},
 {id:7,title:'각진 파란 화병',desc:'둥근 입구와 각진 몸통. 작은 면마다 빛의 색이 달라진다.',labels:['color','shape'],axes:[0,1,2]},
 {id:8,title:'아무것도 쓰지 않은 노트',desc:'크림색 종이와 얇은 스프링. 아직 채워지지 않은 페이지.',labels:['texture','daily'],axes:[2,3,4]},
 {id:9,title:'실버 필름 카메라',desc:'손에 들어오는 작은 크기. 사진 한 장씩 기다리던 시간을 닮은 도구.',labels:['texture','daily'],axes:[2,4,5]},
 {id:10,title:'호피무늬 안경',desc:'투명한 갈색 프레임 속 불규칙한 무늬. 매일 쓰는 작은 물건.',labels:['texture','daily'],axes:[0,2,4,5]},
 {id:11,title:'물결치는 빨간 초',desc:'불을 켜기 전에도 조각 같은 초. 반복되는 곡선과 선명한 빨강.',labels:['color','shape'],axes:[0,1,2]},
 {id:12,title:'초록 소용돌이 문진',desc:'맑은 유리 속에 멈춘 초록 선. 종이를 누르는 작고 묵직한 구체.',labels:['shape','texture'],axes:[0,1,2,4]},
];
const labels = {all:{name:'모든 수집물',en:'Collected things',color:'#e2e1d5',desc:'서로 다른 곳에서 만난 열두 가지 물건.'},daily:{name:'매일 곁에',en:'Everyday companions',color:'#b7c9bf',desc:'자주 손이 가고, 오래 곁에 두고 싶은 것들.'},color:{name:'색을 모으다',en:'A little color',color:'#e6c6cb',desc:'작은 물건 하나로 달라지는 방의 표정.'},shape:{name:'낯선 모양',en:'Unexpected forms',color:'#d6e76b',desc:'익숙한 쓰임에 조금 다른 모양.'},texture:{name:'손끝의 감각',en:'Material memories',color:'#d9cfb8',desc:'표면과 재료, 그 위에 남은 시간.'}};
const drawers=[{name:'일상에서 발견',en:'Everyday discoveries',ids:['daily','color','shape']},{name:'재료와 장면',en:'Materials & memories',ids:['texture','shape','color']},{name:'모두 펼쳐보기',en:'The complete archive',ids:['all','daily','texture']}];
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
let cards=originals.map(c=>({...c,...(saved.cards?.find?.(x=>x.id===c.id)||{}),id:c.id,title:c.title,desc:c.desc,axes:c.axes}));
cards=cards.map(c=>({...c,labels:Array.isArray(c.labels)?c.labels.filter(x=>x!=='all'&&labels[x]):[],verdict:['like','no'].includes(c.verdict)?c.verdict:null,reason:typeof c.reason==='string'?c.reason:''}));
let criterion=typeof saved.criterion==='string'?saved.criterion:'';
let mode=['tray','specimen','collage'].includes(saved.mode)?saved.mode:'tray';
let drawerIndex=0,query='',lastUndo=null,deckId=null,toastTimer,reasonDrafts={};
function persist(){try{localStorage.setItem(KEY,JSON.stringify({cards:cards.map(({id,labels,verdict,reason})=>({id,labels,verdict,reason})),criterion,mode}));return true}catch{toast('저장 공간을 확인해 주세요. 이 창에서만 유지돼요.');return false}}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function selected(id){return cards.filter(c=>id==='all'||c.labels.includes(id))}
function state(){const [route='home',id='all']=location.hash.slice(1).split('/');return{route:['home','collection','deck','taste'].includes(route)?route:'home',id:labels[id]?id:'all'}}
function redraw(fn,focus=false){const change=()=>{fn();if(focus)$('#main').focus({preventScroll:true})};if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches)document.startViewTransition(change);else change()}
function render(){const s=state();document.querySelectorAll('.topbar nav a').forEach(a=>{if(a.hash.split('/')[0]==='#'+s.route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#main').innerHTML=s.route==='home'?home():s.route==='collection'?collection(s.id):s.route==='deck'?deck():taste();bind(s)}
function folder(id,index){const l=labels[id],list=selected(id);return `<button class="folder" data-folder="${id}" aria-label="${l.name} 파일 열기" style="--folder-color:${l.color}"><div class="folder-preview" aria-hidden="true">${list.slice(0,2).map(c=>`<img src="${image(c.id)}" alt="">`).join('')}</div><div class="folder-cover"><span class="mono">FILE ${num(index+1)} / ${num(list.length)} ITEMS</span><h3>${l.name}</h3><p>${l.en}</p><span class="open-mark" aria-hidden="true">↗</span></div></button>`}
function home(){const d=drawers[drawerIndex];return `<div class="page-heading"><div><h1>나의 서랍</h1><p>마음이 머문 것들을, 다시 꺼내 보는 곳.</p></div><span class="serial">A personal collection.</span></div><div class="archive-layout"><aside class="cabinet" aria-label="서랍 선택"><div class="cabinet-note mono"><span>Cabinet 01</span><span>3 drawers</span></div>${drawers.map((d,i)=>`<button class="drawer ${i===drawerIndex?'active':''}" data-drawer="${i}" aria-pressed="${i===drawerIndex}"><span class="drawer-label">${d.name}<small>${num(i+1)}</small></span><span class="handle" aria-hidden="true"></span></button>`).join('')}<p class="cabinet-foot"><span class="line"></span>한 물건이 여러 파일에 있어도<br>내가 남긴 마음은 하나예요.</p></aside><section aria-label="${d.name}의 파일"><div class="shelf-head"><h2>${d.en}</h2><span>서랍 ${num(drawerIndex+1)} · 파일 3개</span></div><div class="folder-shelf">${d.ids.map(folder).join('')}</div><div class="shelf-note"><span>파일을 열어 수집물을 펼쳐보세요.</span><span>12 originals / multiple perspectives</span></div><div class="archive-bottom"><button class="photo-drawer" data-folder="all" aria-label="칸막이 서랍으로 모든 수집물 보기"><img src="./assets/drawer.webp" alt="물건과 종이 조각이 칸마다 담긴 크림색 서랍"><span>서랍 안을 한눈에 ↗</span></button><div class="index-preview"><h3>Index of little things</h3>${['color','shape','texture'].map((id,i)=>`<a class="index-row" href="#collection/${id}"><span>${num(i+1)}</span>${labels[id].name}<span>${num(selected(id).length)} ↗</span></a>`).join('')}<a class="index-row" href="#taste"><span>↳</span>나의 감각을 읽는 중<span>${cards.filter(c=>c.verdict).length}/12</span></a></div></div></section></div>`}
function collection(id){const l=labels[id];return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>${l.name}</span></div><div class="collection-header"><div><h1>${l.name}</h1><p class="subtitle">${l.desc}</p></div><span class="collection-serial">${num(selected(id).length)}</span></div><div class="collection-tools"><nav class="label-tabs" aria-label="라벨 파일">${Object.entries(labels).map(([key,l])=>`<a href="#collection/${key}" ${key===id?'aria-current="page"':''}>${l.name}</a>`).join('')}</nav><div class="view-modes" role="group" aria-label="모음집 보기">${[['tray','칸막이'],['specimen','표본'],['collage','콜라주']].map(([m,t])=>`<button data-mode="${m}" aria-pressed="${mode===m}">${t}</button>`).join('')}</div></div><label class="hint" for="collection-search">이 파일에서 찾기</label><input class="collection-search" id="collection-search" type="search" placeholder="물건 이름으로 찾기" value="${esc(query)}"><div id="collection-objects">${objects(id)}</div><div class="catalog-foot"><span>${l.en} · 같은 물건의 선택과 이유는 모든 파일에 함께 남아요.</span><span>Meonji / ${new Date().getFullYear()}</span></div>`}
function objects(id){const list=selected(id).filter(c=>c.title.includes(query)||c.desc.includes(query));if(!list.length)return `<div class="empty"><h2>아직 이곳에는 없어요.</h2><p>다른 이름으로 찾거나 다른 파일을 펼쳐보세요.</p><button class="link" id="search-reset">검색 지우기</button></div>`;return `<div class="object-grid ${mode}">${list.map(c=>`<button class="object" data-item="${c.id}" aria-label="${c.title} 상세 열기"><div class="object-photo"><img src="${image(c.id)}" alt="${c.title}" loading="lazy"></div><div class="object-meta"><span class="number">${num(c.id)}</span><div><h3>${c.title}</h3><small>${c.labels.map(x=>labels[x].name).join(' · ')}</small></div></div>${c.verdict?`<span class="verdict-stamp" aria-label="${c.verdict==='like'?'좋아요':'아니요'}">${c.verdict==='like'?'O':'X'}</span>`:''}</button>`).join('')}</div>${mode==='tray'?'<div class="tray-front"><span class="handle" aria-hidden="true"></span><small>나의 작은 수집물</small></div>':''}`}
function bind(s){document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>{drawerIndex=+b.dataset.drawer;redraw(render)});document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{query='';location.hash='collection/'+b.dataset.folder});bindObjects();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;persist();redraw(render)});if(s.route==='collection'){$('#collection-search').oninput=e=>{query=e.target.value;$('#collection-objects').innerHTML=objects(s.id);bindObjects()}}if(s.route==='deck')bindDeck();if(s.route==='taste'){$('#criteria-form').onsubmit=e=>{e.preventDefault();criterion=$('#criterion').value.trim();if(persist())toast('내 기준을 남겼어요.');};document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>openItem(+b.dataset.evidence))}}
function bindObjects(){document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>openItem(+b.dataset.item));if($('#search-reset'))$('#search-reset').onclick=()=>{query='';render();$('#collection-search').focus()}}
function openItem(id){const c=cards.find(x=>x.id===id);if(!c)return;$('#item-content').innerHTML=`<button class="close" data-close="item-dialog" aria-label="닫기">×</button><div class="item-layout"><div class="item-visual"><img src="${image(c.id)}" alt="${c.title}"></div><div class="item-detail"><span class="mono">OBJECT ${num(c.id)} · 예시 물건</span><h2 id="item-title">${c.title}</h2><p>${c.desc}</p><div class="tag-list">${c.labels.map(id=>`<a href="#collection/${id}" data-label-link>${labels[id].name} ↗</a>`).join('')}</div><label for="item-reason">이유 한 줄 <span class="hint">(선택)</span></label><input id="item-reason" maxlength="300" placeholder="마음이 움직인 이유가 있다면" value="${esc(reasonDrafts[id]??c.reason??'')}"><div class="decision-buttons"><button data-judge="no"><strong>X</strong>아니요</button><button data-judge="like"><strong>O</strong>좋아요</button></div><p class="hint" id="item-verdict">${c.verdict?`내 선택: ${c.verdict==='like'?'O 좋아요':'X 아니요'}`:'아직 고르지 않았어요.'}</p><div class="membership"><label for="label-select">다른 파일에도 넣기</label><select id="label-select" aria-label="추가할 라벨"><option value="">라벨 선택</option>${Object.entries(labels).filter(([id])=>id!=='all'&&!c.labels.includes(id)).map(([id,l])=>`<option value="${id}">${l.name}</option>`).join('')}</select><button id="attach-label">선택한 파일에 함께 넣기 ＋</button><span class="hint">원본 ${num(c.id)} · 파일 ${c.labels.length}개에 연결</span></div></div></div>`;
 const dialog=$('#item-dialog');if(!dialog.open)dialog.showModal();$('#item-reason').oninput=e=>reasonDrafts[id]=e.target.value;$('#item-content [data-close]').onclick=()=>dialog.close();$('#item-content').querySelectorAll('[data-label-link]').forEach(a=>a.onclick=()=>{query='';dialog.close()});$('#item-content').querySelectorAll('[data-judge]').forEach(b=>b.onclick=()=>{judge(c.id,b.dataset.judge,$('#item-reason').value);openItem(id);$('#item-reason').focus()});$('#attach-label').onclick=()=>{const label=$('#label-select').value;if(!label)return toast('넣을 파일을 골라 주세요.');c.labels.push(label);persist();render();openItem(id);toast('원본 하나를 두 파일에서 볼 수 있어요.');};}
function judge(id,verdict,reason){const c=cards.find(c=>c.id===id);lastUndo={id,verdict:c.verdict,reason:c.reason,draft:reason};c.verdict=verdict;c.reason=reason.trim();delete reasonDrafts[id];const ok=persist();render();if(ok)toast(`${verdict==='like'?'O':'X'} 선택이 연결된 파일에 함께 남았어요.`)}
function deck(){const pending=cards.filter(c=>!c.verdict);const c=pending.find(c=>c.id===deckId)||pending[0];deckId=c?.id;const done=cards.filter(c=>c.verdict).length;return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>취향 고르기</span></div><div class="page-heading"><div><h1>마음에 남나요?</h1><p>이유는 떠오를 때만. 먼저 내 감각으로 골라보세요.</p></div><span class="mono">${num(done)} / 12 CHOICES</span></div>${!c?`<div class="empty"><h2>열두 번의 선택이 모였어요.</h2><p>고른 물건을 다시 펼치거나 감각 분포를 확인해 보세요.</p><a class="primary" href="#taste">나의 감각 보기</a>${lastUndo?'<button id="undo" class="link" style="margin-left:20px">되돌리기</button>':''}</div>`:`<div class="deck-layout"><article class="paper-sheet" id="deck-card" data-card="${c.id}"><span class="mono">OBJECT ${num(c.id)} / YOUR CHOICE</span><div class="deck-photo"><img src="${image(c.id)}" alt="${c.title}"></div><div class="sheet-caption"><h2>${c.title}</h2><span class="mono">${num(c.id)}</span></div></article><div class="deck-info"><h2>A little instinct.</h2><p>${c.desc}</p><div class="progress-track" aria-label="${done}개 판정 완료"><span style="width:${done/12*100}%"></span></div><label for="deck-reason">이유 한 줄 <span class="hint">(선택)</span></label><input id="deck-reason" maxlength="300" placeholder="적지 않아도 괜찮아요" value="${esc(reasonDrafts[c.id]||'')}"><div class="decision-buttons"><button id="choose-no"><strong>X</strong>아니요</button><button id="choose-like"><strong>O</strong>좋아요</button></div><div class="deck-bottom"><button id="undo" ${lastUndo?'':'disabled'}>되돌리기</button><button id="skip-card">지금은 모르겠어요 →</button></div><p class="hint">← X · O → &nbsp; 카드도 좌우로 넘길 수 있어요.</p></div></div>`}`}
function bindDeck(){const c=cards.find(c=>c.id===deckId);if($('#undo'))$('#undo').onclick=()=>{if(!lastUndo)return;const x=cards.find(c=>c.id===lastUndo.id);x.verdict=lastUndo.verdict;x.reason=lastUndo.reason;reasonDrafts[x.id]=lastUndo.draft;deckId=x.id;lastUndo=null;persist();render();toast('직전 선택을 되돌렸어요.')};if(!c||!$('#deck-reason'))return;$('#deck-reason').oninput=e=>reasonDrafts[c.id]=e.target.value;$('#choose-no').onclick=()=>judge(c.id,'no',$('#deck-reason').value);$('#choose-like').onclick=()=>judge(c.id,'like',$('#deck-reason').value);$('#skip-card').onclick=()=>{const pending=cards.filter(c=>!c.verdict);const i=pending.findIndex(x=>x.id===c.id);deckId=pending[(i+1)%pending.length]?.id;render();toast('판정하지 않고 다음 물건으로 넘겼어요.')};const el=$('#deck-card');el.style.touchAction='pan-y';let start;el.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId)};el.onpointerup=e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.3)judge(c.id,dx>0?'like':'no',$('#deck-reason').value)};el.onpointercancel=()=>start=null;}
function profile(){return AXES.map((name,i)=>{const evidence=cards.filter(c=>c.axes.includes(i)&&c.verdict);const likes=evidence.filter(c=>c.verdict==='like').length;return{name,evidence,score:evidence.length>=3?Math.round(likes/evidence.length*100):null}})}
function radar(axes){const center=[210,160],r=105;const point=(i,v)=>{const a=-Math.PI/2+i*Math.PI/3;return[center[0]+Math.cos(a)*r*v,center[1]+Math.sin(a)*r*v]};const pts=v=>axes.map((_,i)=>point(i,v).join(',')).join(' ');return `<svg class="radar" viewBox="0 0 420 325" role="img" aria-label="선택으로 쌓이는 여섯 방향 감각 분포. 근거 3개 미만은 미평가.">${[.25,.5,.75,1].map(v=>`<polygon points="${pts(v)}" fill="none" stroke="#d8d8cd" stroke-width="1"/>`).join('')}${axes.map((a,i)=>{const p=point(i,1),t=point(i,1.29);return `<path d="M210 160 L${p.join(' ')}" stroke="#d8d8cd"/><text x="${t[0]}" y="${t[1]}" text-anchor="middle">${a.name}</text>`}).join('')}${axes.every(a=>a.score!==null)?`<polygon class="radar-value" points="${axes.map((a,i)=>point(i,a.score/100).join(',')).join(' ')}" fill="#d6e76b90" stroke="#545e20" stroke-width="2"/>`:''}${axes.map((a,i)=>{if(a.score===null)return '';const p=point(i,a.score/100);return `<circle cx="${p[0]}" cy="${p[1]}" r="4" fill="#545e20"/>`}).join('')}<circle cx="210" cy="160" r="2" fill="#65675d"/></svg>`}
function taste(){const axes=profile(),judged=cards.filter(c=>c.verdict).length,known=axes.filter(a=>a.score!==null).sort((a,b)=>b.score-a.score);const strong=known.filter(a=>a.score>=60).slice(0,2);const conclusion=strong.length?`${strong.map(a=>a.name).join('과 ')}에서 O 선택이 더 많았어요. 아직 예시 몇 개로 본 초기 관찰이에요.`:judged?`아직 한 방향으로 말하기엔 선택이 더 필요해요.`:'아직 빈 도면이에요. 내 선택이 쌓이면 윤곽이 나타나요.';return `<div class="breadcrumbs"><a href="#home">나의 서랍</a><span>/</span><span>나의 감각</span></div><div class="page-heading"><div><h1>내가 좋아하는 방향</h1><p>기준은 내 말로 남기고, 선택의 결은 여러 방향으로 읽어요.</p></div><span class="serial">A portrait in choices.</span></div><div class="taste-layout"><section class="taste-input"><h2>나의 기준</h2><form id="criteria-form"><label for="criterion">좋아하는 것, 남겨두고 싶은 것을 자유롭게</label><textarea id="criterion" maxlength="1000" placeholder="예를 들면, 매일 쓰는 물건에도 조금 낯선 모양이 있으면 좋겠어. 오래 쓸 수 있고 손에 닿는 느낌이 좋은 것.">${esc(criterion)}</textarea><button class="primary" type="submit">내 기준 남기기</button></form><p class="hint">여기에 한 번만 적어요. 항목을 나누는 일은 결과를 볼 때만 해요.</p><p class="hint">체험판은 예시 물건의 특징과 직접 고른 O/X로 분포를 계산해요. 문장의 자동 해석과 실제 내 수집물 분석은 아직 연결하지 않았어요.</p><a class="index-row" href="#deck">계속 취향 고르기 <span>${judged}/12 →</span></a></section><section class="taste-result" aria-label="감각 분석 결과"><header><h2>My sensibility</h2><span class="mono">${num(judged)} CHOICES</span></header>${radar(axes)}<p class="taste-summary">${conclusion}</p><div class="axis-list">${axes.map(a=>`<details><summary>${a.name}<b>${a.score===null?'미평가':a.score+'%'}</b></summary><p>관련 선택 ${a.evidence.length}개 · O ${a.evidence.filter(c=>c.verdict==='like').length}개</p><ul>${a.evidence.map(c=>`<li><button class="link" data-evidence="${c.id}">${c.title}</button> · ${c.verdict==='like'?'O':'X'}${c.reason?' · '+esc(c.reason):''}</li>`).join('')||'<li>이 축에 연결된 선택이 아직 없어요.</li>'}</ul></details>`).join('')}</div><p class="hint" style="margin-top:20px">축마다 선택 3개부터 O 비율을 표시해요. 빈 축은 0점이 아니에요. 예시 기반 탐색이며 성격·능력 점수가 아니에요.</p></section></div>`}
$('#actual-app').href=APP+'#/list';$('#add-open').onclick=()=>$('#add-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#capture-form').onsubmit=e=>{e.preventDefault();const url=$('#source-url').value;const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))return toast('웹페이지 주소를 넣어 주세요.');location.href=APP+'#/add?'+new URLSearchParams({url})};
document.addEventListener('keydown',e=>{if(e.defaultPrevented||state().route!=='deck'||document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();$(e.key==='ArrowRight'?'#choose-like':'#choose-no')?.click()}});
window.addEventListener('hashchange',()=>{query='';document.querySelectorAll('dialog[open]').forEach(d=>d.close());redraw(render,true);window.scrollTo({top:0,behavior:'instant'})});
window.addEventListener('storage',e=>{if(e.key===KEY)toast('다른 창에서 변경됐어요. 이 창의 입력을 마친 뒤 새로고침해 주세요.')});
render();
